graphql:
  servlet:
    mapping: /graphql
    enabled: true
    cors-enabled: true

graphiql:
  mapping: /graphiql
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.11.11
  endpoint:
    graphql: /graphql

spring:
  data:
    mongodb:
#      authentication-database: admin
      database: local
#      host: localhost
#      port: 27017
#      username: root
#      password: root
      uri: mongodb://root:root@localhost:27017/local
